{
 "title": "Tesla Energy Impact",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Self Powered - All Day",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "consumer_energy_imported_from_battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_battery"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_generator",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_generator"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_grid"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_solar"
      }
     ]
    }
   ]
  },
  {
   "title": "Self Powered - Off Peak",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "consumer_energy_imported_from_battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "off_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_battery"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_generator",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "off_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_generator"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "off_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_grid"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "off_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_solar"
      }
     ]
    }
   ]
  },
  {
   "title": "Self Powered - Partial Peak",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "consumer_energy_imported_from_battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "partial_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_battery"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_generator",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "partial_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_generator"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "partial_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_grid"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "partial_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_solar"
      }
     ]
    }
   ]
  },
  {
   "title": "Self Powered - Peak",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "consumer_energy_imported_from_battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_battery"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_generator",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_generator"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_grid"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_solar"
      }
     ]
    }
   ]
  },
  {
   "title": "Solar Offset",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "consumer_energy_imported_from_battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_battery"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_generator",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_generator"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_grid"
      }
     ]
    },
    {
     "alias": "consumer_energy_imported_from_solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "consumer_energy_imported_from_solar"
      }
     ]
    },
    {
     "alias": "solar_energy_exported",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "solar_energy_exported" }
     ]
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "off_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "solar_energy_exported" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "all_day",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "solar_energy_exported" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "partial_peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "solar_energy_exported" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "peak",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "solar_energy_exported" }
     ]
    }
   ]
  },
  {
   "title": "Backup Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "Outage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "backup",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " * 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "event" }
     ]
    }
   ]
  }
 ]
}